version: "3.0"

services:
  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    networks:
      - atozsports
  
  server:
    build: ./server
    restart: always
    ports:
      - "80:80"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - atozsports
    
  mysql:
    platform: linux/x86_64
    image: mysql
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hi12345!
      - MYSQL_DATABASE=atozsports

networks:
  atozsports: